COMMON_MAKEFILE_DIR = ../CommonMakefile
include $(COMMON_MAKEFILE_DIR)/Makefile_front


INCS = 

OUTPUT= $(LIB_DIR)/TinyXmlLib

#****************************************************************************
# objects 
#****************************************************************************

OBJS = tinyxml.o tinyxmlerror.o tinyxmlparser.o tinystr.o XmlLibVer.o

include $(COMMON_MAKEFILE_DIR)/Makefile_back_lib

